// <auto-generated />
using System;
using Calculador_de_Horas.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Calculador_de_Horas.Migrations
{
    [DbContext(typeof(MyDatabaseContext))]
    partial class MyDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Calculador_de_Horas.Entities.BancoDeHoras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataRegistro");

                    b.Property<int>("FuncionarioId");

                    b.Property<TimeSpan>("HorasExtras");

                    b.Property<string>("Justificativa");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("BancoDeHoras");
                });

            modelBuilder.Entity("Calculador_de_Horas.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CNPJ");

                    b.Property<int>("DiaFechamento");

                    b.Property<string>("RazaoSocial");

                    b.HasKey("Id");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("Calculador_de_Horas.Entities.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Funcao");

                    b.Property<TimeSpan>("HoraAlmocoRetorno");

                    b.Property<TimeSpan>("HoraAlmocoSaida");

                    b.Property<TimeSpan>("HoraIncio");

                    b.Property<TimeSpan>("HoraTermino");

                    b.Property<string>("Nome");

                    b.Property<int>("Registro");

                    b.HasKey("Id");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("Calculador_de_Horas.Entities.HorasFuncionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataRegistro");

                    b.Property<TimeSpan>("Entrada");

                    b.Property<TimeSpan>("Extras");

                    b.Property<int>("FuncionarioId");

                    b.Property<TimeSpan>("Saida");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("HorasFuncionarios");
                });

            modelBuilder.Entity("Calculador_de_Horas.Entities.BancoDeHoras", b =>
                {
                    b.HasOne("Calculador_de_Horas.Entities.Funcionario")
                        .WithMany("BancoDeHoras")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Calculador_de_Horas.Entities.HorasFuncionario", b =>
                {
                    b.HasOne("Calculador_de_Horas.Entities.Funcionario")
                        .WithMany("CartaoPonto")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
